### ISSUE TITLE
Description of class ids

### ISSUE THREAD

**Issue by machar94** [deeepwin/lego-cnn#2]
Hello and happy holidays. Was wondering if you had a list of class ids to lego types? At first glance, it seems that the class is color invariant and it just depends on the shape of the lego. I wanted to know if other than just going through the training images, was there somewhere you had documented which class id corresponds with which lego. I'm looking to run inference on a couple of my own images and am at the stage where I am tagging the images using the VGG Image Annotator and need to provide a class id in the region attribute. Thanks for your help.

**Comment by deeepwin** [comment]
Thanks for your interest. I used to have a print out with a look-up between the lego class ids and lego type numbers. Unfortunately, I cannot find it anymore. But, since you want to annotate new images anyway, use:

https://www.robots.ox.ac.uk/~vgg/software/via/

and the via project file for the eval images that I have just uploaded:

datasets/lego/eval/via_project_lego.json

You then need to download the dataset from kaggle

https://www.kaggle.com/marwin1665/synthetic-lego-images-images22

to get the eval images in the folder datasets/lego/eval and then open the via application in your browser and load the json project file. It cannot find the images automatically, hence you need to select them manually. The result looks like that:

![grafik](https://user-images.githubusercontent.com/65670300/103131015-584b3400-469f-11eb-8732-e173f03f6367.png)

Regarding your second question about color invariance. The network is trained with images that have different colors for the same class id. Which means, it should be color insensitive. The goal is to detect a lego based on its shape, not color. Once the network has detected the correct class id (lego type) it would be easy to retrieve the correct color of the lego. 

Neverthless, color could be a very important factor for the RPN network itself, not the classification network. The RPN wants to locate an object. Color would be a very nice feature to distinguish legos for that task. A CNN should be color sensitive in principle. I tried once to play around with that to improve the RPN preformance, but there results were not better. It appeared, that the CNN never really got color sensitive, but rather focused on local lego features.

Wish you nice Holidays.

**Comment by deeepwin** [comment]
Maybe that helps as well, summary with pictures:$

[legos.pdf](https://github.com/deeepwin/lego-cnn/files/5741759/legos.pdf)

**Comment by machar94** [comment]
Thanks for the pdf! It confirmed what I was able to dig up from the inference results of the evaluation images. 

I thought it would be a fun project to get something like this working and then translate it over to an iPhone app where you could point at a lego block and get the block ID. My first task was to just get inference working on a couple of my own iPhone photos. I managed to resize my images and run the model. I have my results located in my fork: https://github.com/machar94/lego-cnn/blob/master/notes.md. I thought the RPN regions proposed weren't so bad, but the class labels in the second image were extremely off. I'm thinking it's mostly because of the way I resized. iPhone images I took were 3:4 and so I transposed the imaged and then scaled it down to 800 x 600. I think perhaps the phone perspective may be the issue.

Don't have too much experience with the MRCNN, but that's what I hope to dig into now. I'll let you know if I have some ideas for improving it.
